################################################################################
#
# This file has been generated by SpyGlass:
#     Report Created by: s284963
#     Report Created on: Wed Jan 12 16:32:44 2022
#     Working Directory: /home/s284963/riscv_testing_2021_zoix/syn/run/_snpDft_s284963.973.0
#     Report Location  : ./sg_config/riscv_core_0_128_1_16_1_1_0_0_0_0_0_0_0_0_0_3_6_15_5_1a110800/sg_dft_testpoint_analysis/spyglass_reports/dft/dft_generated_dc_constraints.tcl
#     SpyGlass Version : SpyGlass_vR-2020.12
#     Policy Name      : dft(SpyGlass_vR-2020.12)
#     Comment          : Generated by rule Info_generated_reports
#
################################################################################

################################################################################
# Begin data for design unit: riscv_core_0_128_1_16_1_1_0_0_0_0_0_0_0_0_0_3_6_15_5_1a110800
################################################################################

 current_design riscv_core_0_128_1_16_1_1_0_0_0_0_0_0_0_0_0_3_6_15_5_1a110800
  set_dft_signal -type MasterClock -port clk_i -timing [list 45 55]
  set_dft_signal -type Reset -port rst_ni -active_state 1
  set_dft_signal -type ScanEnable -port test_en_i -active_state 1
  set_dft_signal -type Constant -port test_mode_tp -active_state 1
################################################################################
# End data for design unit: riscv_core_0_128_1_16_1_1_0_0_0_0_0_0_0_0_0_3_6_15_5_1a110800
################################################################################

