add wave -noupdate /LBIST_testbench/stimuli/clk
add wave -noupdate /LBIST_testbench/stimuli/reset
add wave -noupdate /LBIST_testbench/stimuli/q
add wave -noupdate /LBIST_testbench/dut/clk_i
add wave -noupdate /LBIST_testbench/dut/rst_ni
add wave -noupdate /LBIST_testbench/dut/test_en_i
add wave -noupdate /LBIST_testbench/dut/test_mode
add wave -noupdate /LBIST_testbench/dut/test_si1
add wave -noupdate /LBIST_testbench/dut/test_si2
add wave -noupdate /LBIST_testbench/dut/test_si3
add wave -noupdate /LBIST_testbench/dut/test_si4
add wave -noupdate /LBIST_testbench/dut/test_si5
add wave -noupdate /LBIST_testbench/dut/test_si6
add wave -noupdate /LBIST_testbench/dut/test_si7
add wave -noupdate /LBIST_testbench/dut/test_si8
add wave -noupdate /LBIST_testbench/dut/test_si9
add wave -noupdate /LBIST_testbench/dut/test_si10
add wave -noupdate /LBIST_testbench/dut/test_si11
add wave -noupdate /LBIST_testbench/dut/test_si12
add wave -noupdate /LBIST_testbench/dut/test_si13
add wave -noupdate /LBIST_testbench/dut/test_si14
add wave -noupdate /LBIST_testbench/dut/test_si15
add wave -noupdate /LBIST_testbench/dut/test_si16
add wave -noupdate /LBIST_testbench/dut/test_so1
add wave -noupdate /LBIST_testbench/dut/test_so2
add wave -noupdate /LBIST_testbench/dut/test_so3
add wave -noupdate /LBIST_testbench/dut/test_so4
add wave -noupdate /LBIST_testbench/dut/test_so5
add wave -noupdate /LBIST_testbench/dut/test_so6
add wave -noupdate /LBIST_testbench/dut/test_so7
add wave -noupdate /LBIST_testbench/dut/test_so8
add wave -noupdate /LBIST_testbench/dut/test_so9
add wave -noupdate /LBIST_testbench/dut/test_so10
add wave -noupdate /LBIST_testbench/dut/test_so11
add wave -noupdate /LBIST_testbench/dut/test_so12
add wave -noupdate /LBIST_testbench/dut/test_so13
add wave -noupdate /LBIST_testbench/dut/test_so14
add wave -noupdate /LBIST_testbench/dut/test_so15
add wave -noupdate /LBIST_testbench/dut/test_so16
